import { useEffect } from "react";
import { useNavbarButtons } from "../widgets/NavbarButtonsContext";
import schoolJson from "@shared/jsons/schools.json";
import {
  Bmsh,
  Ccsh,
  Cjshs,
  Dwsh,
  Hhsh,
  Hhvs,
  Hkhs,
  Hyivs,
  Hysh,
  Kmsh,
  Lmsh,
  Mdsh,
  Nkhs,
  Nnkieh,
  Nnsh,
  Pmai,
  Sfsh,
  Tcjh,
  Tncvs,
  Tnssh,
  Tntcshsa,
  Tnvs,
  Twais,
  Twvs,
  Yhsh,
  Yrhs,
} from "@icons";

// NOTE: I KNOW ITS BASICALLY SHIT, BUT ITS GENERATED BY AI AND I TOOK 0 EFFORT SO uhh lets use it
const schoolIconClassName = "w-14 h-14";
const SchoolIcons = [
  <Bmsh className={schoolIconClassName} />,
  <Ccsh className={schoolIconClassName} />,
  <Cjshs className={schoolIconClassName} />,
  <Dwsh className={schoolIconClassName} />,
  <Hhsh className={schoolIconClassName} />,
  <Hhvs className={schoolIconClassName} />,
  <Hkhs className={schoolIconClassName} />,
  <Hyivs className={schoolIconClassName} />,
  <Hysh className={schoolIconClassName} />,
  <Kmsh className={schoolIconClassName} />,
  <Lmsh className={schoolIconClassName} />,
  <Mdsh className={schoolIconClassName} />,
  <Nkhs className={schoolIconClassName} />,
  <Nnkieh className={schoolIconClassName} />,
  <Nnsh className={schoolIconClassName} />,
  <Pmai className={schoolIconClassName} />,
  <Sfsh className={schoolIconClassName} />,
  <Tcjh className={schoolIconClassName} />,
  <Tncvs className={schoolIconClassName} />,
  <Tnssh className={schoolIconClassName} />,
  <Tntcshsa className={schoolIconClassName} />,
  <Tnvs className={schoolIconClassName} />,
  <Twais className={schoolIconClassName} />,
  <Twvs className={schoolIconClassName} />,
  <Yhsh className={schoolIconClassName} />,
  <Yrhs className={schoolIconClassName} />,
];
const schoolAbbreviations = [
  "Bmsh",
  "Ccsh",
  "Cjshs",
  "Dwsh",
  "Hhsh",
  "Hhvs",
  "Hkhs",
  "Hyivs",
  "Hysh",
  "Kmsh",
  "Lmsh",
  "Mdsh",
  "Nkhs",
  "Nnkieh",
  "Nnsh",
  "Pmai",
  "Sfsh",
  "Tcjh",
  "Tncvs",
  "Tnssh",
  "Tntcshsa",
  "Tnvs",
  "Twais",
  "Twvs",
  "Yhsh",
  "Yrhs",
].map((i) => i.toLowerCase());
const SchoolIcon = ({ abbreviation }: { abbreviation: string }) => {
  if (!schoolAbbreviations.includes(abbreviation)) return null;
  return SchoolIcons[schoolAbbreviations.findIndex((a) => a === abbreviation)];
};

const Schools = () => {
  const { setNavbarButtonsByType, setNavbarTitle } = useNavbarButtons();

  useEffect(() => {
    setNavbarButtonsByType(["logo", "themeToggle"]);
    setNavbarTitle(undefined);
  }, []);

  return (
    <div className="pt-18 flex flex-col items-center min-h-screen bg-base-300">
      <ul className="mx-auto max-w-lg w-full grid grid-cols-2 lg:grid-cols-3 p-4 gap-4">
        {schoolJson.map((school) => (
          <li key={school.abbreviation}>
            <div className="w-full flex flex-col items-center justify-center bg-base-100 py-4 rounded-box">
              <div className="p-3 bg-white rounded-full overflow-clip">
                <SchoolIcon abbreviation={school.abbreviation} />
              </div>
              <p>{school.name}</p>
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Schools;
