// scripts/prebuild.js
const { mkdirSync, readdirSync, readFileSync, writeFileSync } = require('node:fs');
const { resolve, basename } = require('node:path');

// 設定來源與目標目錄
const sourcePromptsDir = resolve(process.cwd(), 'shared/prompts');
const sourceImagesDir = resolve(process.cwd(), 'shared/images/post-templates');
const sourceTemplatesDir = resolve(process.cwd(), 'shared/templates');

const generatedDir = resolve(process.cwd(), 'src/generated');
mkdirSync(generatedDir, { recursive: true });

const toConstantName = (fileName) =>
  basename(fileName)
    .replace(/\.[^/.]+$/, '')
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toUpperCase();

// 輔助函式：將檔案清單寫入獨立的 .ts 檔案
function generateTsFile(outputPath, files, readContentFn, groupExportName) {
  let content = `// AUTO-GENERATED FILE. DO NOT EDIT.\n// Generated by scripts/prebuild.js\n\n`;
  const constants = [];

  for (const file of files) {
    const constantName = toConstantName(file);
    const value = readContentFn(file);
    content += `export const ${constantName}: string = ${JSON.stringify(value)};\n\n`;
    constants.push(constantName);
  }

  content += `export const ${groupExportName} = {\n`;
  for (const name of constants) {
    content += `  ${name},\n`;
  }
  content += `} as const;\n`;

  writeFileSync(outputPath, content);
}

// ==========================================
// 1. Prompts -> src/generated/prompts.ts
// ==========================================
const promptFiles = readdirSync(sourcePromptsDir).filter((file) => file.endsWith('.md'));
generateTsFile(
  resolve(generatedDir, 'prompts.ts'),
  promptFiles,
  (file) => readFileSync(resolve(sourcePromptsDir, file), 'utf8'),
  'prompts'
);

// ==========================================
// 2. Images (Base64) -> src/generated/images.ts
// ==========================================
const imageFiles = readdirSync(sourceImagesDir).filter((file) => file.endsWith('.webp'));
const MAX_IMAGE_SIZE = 50 * 1024; // 50 KB

generateTsFile(
  resolve(generatedDir, 'images.ts'),
  imageFiles,
  (file) => {
    const filePath = resolve(sourceImagesDir, file);
    const buffer = readFileSync(filePath);

    if (buffer.length > MAX_IMAGE_SIZE) {
      const sizeInKB = (buffer.length / 1024).toFixed(2);
      console.error(`[ERROR] 圖片過大: ${file} (${sizeInKB} KB > 50 KB)`);
    }

    return `data:image/webp;base64,${buffer.toString('base64')}`;
  },
  'images'
);

// ==========================================
// 3. HTML Templates -> src/generated/templates.ts
// ==========================================
const htmlFiles = readdirSync(sourceTemplatesDir).filter((file) => file.endsWith('.html'));
generateTsFile(
  resolve(generatedDir, 'templates.ts'),
  htmlFiles,
  (file) => readFileSync(resolve(sourceTemplatesDir, file), 'utf8'),
  'templates'
);

console.log(
  `Generated: ${promptFiles.length} prompts, ${imageFiles.length} images (Base64), and ${htmlFiles.length} HTML templates.`
);