// scripts/prebuild.js
const { mkdirSync, readdirSync, readFileSync, writeFileSync } = require('node:fs');
const { resolve, basename } = require('node:path');

const sourceDir = resolve(process.cwd(), 'shared/prompts');
const outputFile = resolve(process.cwd(), 'src/generated/prompts.ts');

mkdirSync(resolve(process.cwd(), 'src/generated'), {
  recursive: true,
});

const toConstantName = (fileName) =>
  basename(fileName, '.md')
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toUpperCase();

const files = readdirSync(sourceDir).filter((file) => file.endsWith('.md'));

let output = `// AUTO-GENERATED FILE.
// DO NOT EDIT.
// Generated by scripts/prebuild.js

`;

for (const file of files) {
  const constantName = toConstantName(file);
  const content = readFileSync(resolve(sourceDir, file), 'utf8');

  output += `export const ${constantName} = ${JSON.stringify(content)};\n\n`;
}

output += 'export const prompts = {\n';

for (const file of files) {
  const constantName = toConstantName(file);
  output += `  ${constantName},\n`;
}

output += '} as const;\n';

writeFileSync(outputFile, output);

console.log(`Generated ${files.length} prompts.`);
